# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b42ad5ecb4de4a2e8af7f4c0c722abb93f79d6aab7b8dd948de01b8f3d6c55fb7e1468e4447528a937c5e494b5c81fd82166c5b805cdcbaff35b44c49b1ee64

test:
  secret_key_base: ff69890a9e2a444eb185e10f4ec487df1d5c1ccdedf27e00129204844ae4a325d5a129170fb410a499b3bb6f24e082dd8f7c87e24df202effb7f360f2a33fccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
